PYTHON-DJANGO/multiple_app_assignment/apps/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^add_course$', views.create, name='create' ),
    url(r'^users_courses$', views.users_courses, name='users_courses'),
    url(r'^courses/destroy/(?P<id>\d+)$', views.destroy, name='destroy')

]

PYTHON-DJANGO/multiple_app_assignment/multiple_app_assignment/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'login_registration/', include('apps.login_registration.urls', namespace="login_registration")),
    url(r'^courses/', include('apps.courses.urls', namespace="courses")),
    url(r'^timedisplay/', include('apps.timedisplay.urls', namespace="timedisplay")),
    url(r'^disappearing_ninjas/', include('apps.disappearing_ninjas.urls', namespace="disappearing_ninjas")),
    url(r'^survey_form/', include('apps.survey_form.urls', namespace="survey_form")),
    url(r'^', include('apps.multiple_apps.urls', namespace="multiple_apps")),

]

PYTHON-DJANGO/multiple_app_assignment/apps/courses/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Count
from ..login_registration.models import User
from django.contrib import messages


class CourseManager(models.Manager):

    def enroll_user(self, postData):

        # validate option input, if passed empty "" value for either course or user, return false, and show error message
        if not postData['course'] or not postData['user']:

            return ('Empty', 'Please select a valid user and course')

        # add the user to the course
        else:
            course_id = int(postData['course'])
            user_id = int(postData['user'])

            user = User.objects.get(id=user_id)
            course = Course.objects.get(id=course_id)

            # check if user already in course
            # if already in course, return False and message
            # else add to course, return True and message
            users = course.users.filter(id=user_id)

            if users:
                print '*'*50
                print users
                print '*'*50
                return (False, {'user': user.first_name, 'course': course.name })
            else:
                course.users.add(user)

        # return success message
        return (True, {'user': user.first_name, 'course': course.name })


class Course(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(User, related_name="courses")
    objects = CourseManager()

    def __str__(self):
        return self.name

class Description(models.Model):
    description = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    course = models.OneToOneField(Course)


    def __str__(self):
        return self.name

PYTHON-DJANGO/multiple_app_assignment/apps/courses/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Count
from .models import Course, Description
from ..login_registration.models import User

def index(request):

    if 'user' not in request.session:

        return redirect('login_registration:index')

    # get courses and descriptions
    context = {

        'courses': Course.objects.all().order_by('name'),
        'description': Description.objects.all()

    }

    return render(request, 'courses/index.html', context)


def create(request):

    # do basic validation on form name
    if len(request.POST['name']) < 2:
        messages.error(request, 'Enter valid course name')
        return redirect('courses:index')

    context = {

        'name': request.POST['name'],
        'description': request.POST['description'] # we are going to add description even if empty

    }

    # create new course
    course = Course.objects.create(name=context['name'])

    # add the course's description, using the newly created course's ID
    Description.objects.create(description=context['description'], course=course)

    return redirect('courses:index')



def destroy(request, id):

    # show the course name and description to user and confirm deletion
    # NO button will redirect to main course page
    # YES button will delete the course record from DB and redirect to main course page
    if request.method == 'GET':

        context = {

            'id': id,
            'course': Course.objects.get(id=id)

        }

        return render(request, 'courses/confirm_delete.html', context)

    else:

        Course.objects.get(id=id).delete()
        return redirect('courses:index')


def users_courses(request):

    if request.method == 'POST':

        # query DB to enroll User into Course
        response = Course.objects.enroll_user(request.POST)

        # check response from query, if Empty or False return error messages
        # if True, show success message,
        if response[0] == 'Empty':
            messages.error(request, response[1])

        elif response[0] == False:
            messages.error(request, '{} is already enrolled in {}'.format(response[1]['user'], response[1]['course']))

        else:
            messages.success(request, '{} was successfully added to {}'.format(response[1]['user'], response[1]['course']))

    # query DB to get all course info and number of users currently enrolled in each course
    context = {
        'users': User.objects.all().order_by('first_name', 'last_name'),
        'courses': Course.objects.annotate(num_users=Count('users')).order_by('name')
    }


    return render(request, 'courses/users_courses.html', context)

PYTHON-DJANGO/multiple_app_assignment/apps/courses/templates/courses/confirm_delete.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Delete a course</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'courses/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h3>Are you sure you want to delete the following course?</h3>
            <div class="row">
                <p>Name:</p>
                <p>{{ course.name }}</p>
            </div>
            <div class="row">
                <p>Description:</p>
                <p>{{ course.description.description }}</p>
            </div>
            <div class="row">
                <form action="{% url 'courses:index' %}" method="GET">
                    <input class="btn back" type="submit" value="No">
                </form>
                <form action="{% url 'courses:destroy' id=id %}" method="POST">
                    {% csrf_token %}
                    <input class="btn delete" type="submit" value="Yes! I want to delete this">
                </form>
            </div>
        </div>
    </body>
</html>

PYTHON-DJANGO/multiple_app_assignment/apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Language" content="en">
        <title>Add a new course</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'courses/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <div class="add_new">
                <h3>Add a new course</h3>
                {% if messages %}
                    {% for message in messages %}
                        <p class="error">{{ message }}</p>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'courses:create' %}" method="POST">
                    {% csrf_token %}
                    <label for="name">Name:</label>
                    <input id="name" type="text" name="name">
                    <label for="description">Description:</label>
                    <textarea id="description" name="description"></textarea>
                    <input class="btn add" type="submit" value="Add">
                </form>
            </div>
            <div class="show_table">
                <h3>Courses</h3>
                <table>
                    <thead>
                        <tr>
                            <td class="col1">Course Name</td>
                            <td class="col2">Description</td>
                            <td class="col3">Date Added</td>
                            <td class="col4">Actions</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% if courses %}
                            {% for course in courses %}
                                <tr>
                                    <td>{{ course.name }}</td>
                                    <td> {{ course.description.description }}</td>
                                    <td>{{ course.created_at }}</td>
                                    <td><a href="{% url 'courses:users_courses' %}">enroll</a> <a href="{% url 'courses:destroy' id=course.id %}">remove</a> </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </body>
</html>

PYTHON-DJANGO/multiple_app_assignment/apps/courses/templates/courses/users_courses.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>User Courses</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'courses/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            {% if messages %}
                {% for message in messages %}
                    <p class="{{ message.tags }}">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <form action="{% url 'courses:users_courses' %}" method="POST">
                {% csrf_token %}
                <select name="user">
                    <option value="" selected>Select User</option>
                    {% if users %}
                        {% for user in users %}
                            <option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }}</option>
                        {% endfor %}
                    {% endif %}
                </select>
                <select name="course">
                    <option value="" selected>Select Course</option>
                    {% if courses %}
                        {% for course in courses %}
                            <option value="{{ course.id }}">{{ course.name }}</option>
                        {% endfor %}
                    {% endif %}
                </select>
                <input class="btn add_user_to_course" type="submit" value="Add User to Course">
            </form>
            <table class="user_course_table">
                <tr>
                    <thead>
                        <td class="col1">Course</td>
                        <td class="col2">Title</td>
                        <td class="col3">Number of Users</td>
                    </thead>
                </tr>
                <tbody>
                    {% if courses %}
                    {% for course in courses %}
                        <tr>
                            <td>{{ course.id }}</td>
                            <td>{{ course.name }}</td>
                            <td>{{ course.num_users }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
            <a class="return" href="{% url 'courses:index' %}">&#8249;Return Home</a>

        </div>

    </body>
</html>