PYTHON-DJANGO/semi_restful_routes_assignment/apps/semi_restful_routes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^/$', views.index, name="index"), #GET -- retrieve all products
    url(r'^/new$', views.new, name="new"), #GET -- display form to create a new products
    url(r'/products', views.create, name="create"), #POST -- create a new products
    url(r'/(?P<id>\d+)$', views.show, name="show"), #GET -- show specific product
    url(r'/(?P<id>\d+)/edit$', views.edit, name="edit"), #GET -- show form to edit specific product
    url(r'/(?P<id>\d+)/update$', views.update, name="update"), #POST -- update specific product
    url(r'/(?P<id>\d+)/destroy$', views.destroy, name="destroy"), #POST -- delete specific product

]

PYTHON-DJANGO/semi_restful_routes_assignment/semi_restful_routes_assignment/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^products', include('apps.semi_restful_routes.urls', namespace="products"))
]

PYTHON-DJANGO/semi_restful_routes_assignment/apps/semi_restful_routes/models.py
from __future__ import unicode_literals
from django.db import models
import re
from decimal import *

price_regex = re.compile(r'^\d+[.]?[\d]?[\d]?$')

class ProductManager(models.Manager):

    def new(self, postData):

        # validate form data
        # a tuple is returned in the format of (Bool, messages)
        #   if False, then don't add to DB
        #   if True, messages will be an empty list, add product to DB, and add a success message to list
        # return the response
        response = self.validate_product(postData)

        if response[0] == False:
            return response

        else:

            # add product to DB
            Product.objects.create(name=postData['name'], description=postData['description'], price=Decimal(postData['price']))

            response[1].append('Successfully added {}'.format(postData['name']))

            return response


    def edit(self, id, postData):

        response = self.validate_product(postData)

        if response[0] == False:

            return response

        else:
            product = Product.objects.get(id=id)

            product.name = postData['name']
            product.description = postData['description']
            product.price = Decimal(postData['price'])
            product.save()

            response[1].append('Product id {} ({}) successfully updated'.format(id, product.name))

            return response


    def validate_product(self, postData):

        messages = []

        # basic validations
        if postData['name'] == "":
            messages.append('Name cannot be blank')

        if postData['description'] == "":
            messages.append('Description cannot be blank')

        if postData['price'] == "":
            messages.append('Price cannot be blank')

        elif not re.match(price_regex, postData['price']):
            messages.append('Please enter price in format 0.00')

        if messages:
            return (False, messages)

        else:
            return (True, messages)


    def destroy(self, id):

        Product.objects.get(id=id).delete()



class Product(models.Model):

    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProductManager()

    def __str__(self):
        print self.name

PYTHON-DJANGO/semi_restful_routes_assignment/apps/semi_restful_routes/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.contrib import messages

def index(request):

    # GET -- show all products
    if request.method != 'GET':

        return redirect('products:index')


    else:

        context = {

            'products': Product.objects.all()

        }

        request.session['last_url'] = 'products:index'

        return render(request, 'semi_restful_routes/index.html', context)


def new(request):

    # GET -- display form to add new product
    if request.method != 'GET':
        return redirect('products:index')

    else:

        return render(request, 'semi_restful_routes/new.html')


def create(request):

    # POST -- add new product

    if request.method != 'POST':


        return redirect('products:index')

    else:

        response = Product.objects.new(request.POST)

        if response[0] == False:
            for message in response[1]:
                messages.error(request, message)
            return redirect('products:new')

        else:
            for message in response[1]:
                messages.success(request, message)
            return redirect('products:index')


def show(request, id):

    # GET -- show specific product
    if request.method != 'GET':
        return redirect('products:index')

    else:
        context = {

            'product': Product.objects.get(id=id)

        }

        return render(request, 'semi_restful_routes/show.html', context)


def edit(request, id):

    try:

        print '*'*50
        print request.META['HTTP_REFERER']
        print '*'*50

    except:
        pass

    # GET -- display form to edit specific product
    if request.method != 'GET':
        return redirect('products:index')

    else:

        context = {

            'product': Product.objects.get(id=id)
        }

        return render(request, 'semi_restful_routes/edit.html', context)


def update(request, id):

    # POST -- update specific product
    if request.method != 'POST':

        return redirect('products:index')

    else:

        response = Product.objects.edit(id, request.POST)

        if response[0] == False:

            for message in response[1]:
                messages.error(request, message)

            return redirect('products:edit', id=id)

        else:

            for message in response[1]:
                messages.success(request, message)

            return redirect('products:index')


def destroy(request, id):

    # POST -- delete specific product
    if request.method != 'POST':
        return redirect('products:index')

    else:
        Product.objects.destroy(id)
        return redirect('products:index')

PYTHON-DJANGO/semi_restful_routes_assignment/apps/semi_restful_routes/templates/semi_restful_routes/edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Edit Product {{ product.id }} | Semi Restful Route Demo</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'semi_restful_routes/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h3>Edit Product {{ product.id }}</h3>
            {% if messages %}
            <div class="flash_message">
                {% for message in messages %}
                    {% if message.tags %}
                    <p class={{ message.tags }}>{{ message }}</p>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <form class="product" action="{% url 'products:update' id=product.id %}" method="POST">
                {% csrf_token %}
                <label for="name">Name</label>
                <input type="text" name="name" value="{{ product.name }}">
                <label for="description">Description</label>
                <input type="text" name="description" value="{{ product.description }}">
                <label for="price">Price</label>
                <input type="text" name="price" value="{{ product.price }}">
                <input class="btn" type="submit" value="Update">
            </form>
            <div class="links">
                <a href="{% url 'products:index' %}">Show</a> | <a href="{{ request.META.HTTP_REFERER }}">Back</a>
            </div>
        </div>

    </body>
</html>

PYTHON-DJANGO/semi_restful_routes_assignment/apps/semi_restful_routes/templates/semi_restful_routes/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>All Products | Semi Restful Routes Demo</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'semi_restful_routes/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h3>Products</h3>
            {% if messages %}
            <div class="flash_message">
                {% for message in messages %}
                    {% if message.tags %}
                        <p class="{{ message.tags }}">{{ message }}</p>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <table>
                <tr>
                    <thead>
                        <td class="col1">Name</td>
                        <td class="col2">Description</td>
                        <td class="col3">Price</td>
                        <td class="col4">Actions</td>
                    </thead>
                </tr>
                <tbody>
                    {% if products %}
                        {% for product in products %}
                        <tr>
                            <td>{{ product.name }}</td>
                            <td>{{ product.description }}</td>
                            <td>${{ product.price }}</td>
                            <td>
                                <div class="table_links">
                                    <a href="{% url 'products:show' id=product.id %}">Show</a> | <a href="{% url 'products:edit' id=product.id %}">Edit</a>
                                    <form action="{% url 'products:destroy' id=product.id %}" method="POST">
                                        {% csrf_token %}
                                        <input class="btn" type="submit" value="Remove">
                                    </form>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
            <a href="{% url 'products:new' %}">Add a new product</a>
        </div>
    </body>
</html>

PYTHON-DJANGO/semi_restful_routes_assignment/apps/semi_restful_routes/templates/semi_restful_routes/new.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Create a new product | Semi Restful Route Demo</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'semi_restful_routes/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h3>Add a new product</h3>
            {% if messages %}
            <div class="flash_message">
                {% for message in messages %}
                    {% if message.tags %}
                        <p class="{{ message.tags }}">{{ message }}</p>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <form class="product" action="{% url 'products:create' %}" method="POST">
                {% csrf_token %}
                <label for="name">Name</label>
                <input type="text" name="name">
                <label for="description">Description</label>
                <input type="text" name="description">
                <label for="price">Price</label>
                <input type="text" name="price">
                <input class="btn" type="submit" value="Create">
            </form>
            <a href="{% url 'products:index' %}">Go back</a>
        </div>

    </body>
</html>

PYTHON-DJANGO/semi_restful_routes_assignment/apps/semi_restful_routes/templates/semi_restful_routes/show.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Product {{ product.id }} Info | Semi Restful Routes Demo</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'semi_restful_routes/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h3>Product {{ product.id }}</h3>
            <div class="show_product">
                <p>Name:</p>
                <p>{{ product.name }}</p>
            </div>
            <div class="show_product">
                <p>Description:</p>
                <p>{{ product.description }}</p>
            </div>
            <div class="show_product">
                <p>Price</p>
                <p>{{ product.price }}</p>
            </div>
            <div class="links">
                <a href="{% url 'products:edit' id=product.id %}">Edit</a> | <a href="{{ request.META.HTTP_REFERER }}">Back</a>
            </div>
        </div>
    </body>
</html>