PYTHON-DJANGO/multiple_app_assignment/apps/survey_form/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.index, name="index"),
    url(r'^result$', views.result, name="result"),
    url(r'^surveys/process', views.process_survey, name="process_survey")

]

PYTHON-DJANGO/multiple_app_assignment/multiple_app_assignment/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'login_registration/', include('apps.login_registration.urls', namespace="login_registration")),
    url(r'^courses/', include('apps.courses.urls', namespace="courses")),
    url(r'^timedisplay/', include('apps.timedisplay.urls', namespace="timedisplay")),
    url(r'^disappearing_ninjas/', include('apps.disappearing_ninjas.urls', namespace="disappearing_ninjas")),
    url(r'^survey_form/', include('apps.survey_form.urls', namespace="survey_form")),
    url(r'^', include('apps.multiple_apps.urls', namespace="multiple_apps")),

]

PYTHON-DJANGO/multiple_app_assignment/apps/survey_form/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

PYTHON-DJANGO/multiple_app_assignment/apps/survey_form/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

def index(request):

    # show survey form to user
    return render(request, 'survey_form/index.html')


def result(request):

    # show survey results to user
    return render(request, 'survey_form/result.html')


def process_survey(request):

    # if you made it to this route with a POST request
    # do basic validation on name field, if blank return to survey and show error message
    # otherwise process survey form, adding all values to session and incrementing count each time form submitted

    if request.method == 'POST':

        if request.POST['name'] == "":
            messages.error(request, "Name field can not be blank")
            return redirect ('survey_form:index')

        else:

            request.session['name'] = request.POST['name']
            request.session['location'] = request.POST['location']
            request.session['language'] = request.POST['language']
            request.session['comment'] = request.POST['comment']

        if 'count' not in request.session:
            request.session['count'] = 1
        else:
            request.session['count'] += 1

        return redirect('survey_form:result')

    # else redirect to index.html and show survey form
    else:

        return redirect('survey_form:index')

PYTHON-DJANGO/multiple_app_assignment/apps/survey_form/templates/survey_form/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Survey Form</title>
        <style media="screen">
            * {
                margin: 0;
                padding: 0;
                font-family: monospace;
            }

            .wrapper {
                width: 400px;
                margin: 0 auto;
                padding: 20px;
            }

            .survey {
                margin: 0 auto;
                padding: 12px;
                border: 1px solid black;
                width: 325px;
                box-sizing: border-box;
            }


                label {
                    line-height: 25px;
                    vertical-align: bottom;
                    margin-top: 8px;
                }

                input, select {
                    height: 25px;
                }

                input {
                    padding-left: 4px;
                }

                textarea {
                    display: block;
                    width: 100%;
                    height: 50px;
                    padding: 4px;
                    box-sizing: border-box;
                    resize: none;
                }

                .col1 {
                    width: 48%;
                    display: inline-block;
                    box-sizing: border-box;

                }


                .col2 {
                    margin-left: 1px;
                    display: inline-block;
                    width: 49%;
                    border: 1px solid black;
                    box-sizing: border-box;

                }

                .btn {
                    margin-top: 12px;
                    width: 20%;
                    height: 20px;
                    border: 2px solid black;
                    box-shadow: 2px 2px black;
                    color: white;
                    background-color: #2b78e4;
                    margin-left: 80%;
                }

                p.error {
                    color: red;
                    text-align: center;
                    margin-bottom: 8px;
                }
        </style>
    </head>
    <body>
        <div class="wrapper">
            <div class="survey">
                {% if messages %}
                    {% for message in messages %}
                        <p class="error">{{ message }}</p>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'survey_form:process_survey' %}" method="POST">
                    {% csrf_token %}
                    <label class="col1" id="name" for="name">Your Name:</label>
                    <input class="col2" type="text" name="name">
                    <label class="col1" id="location" for="location">Dojo Location:</label>
                    <select class="col2" name="location">
                        <option value="Berkeley">Berkeley</option>
                        <option value="Chicago">Chicago</option>
                        <option value="Dallas">Dallas</option>
                        <option value="Los Angeles">Los Angeles</option>
                        <option value="Orange County">Orange County</option>
                        <option value="Seattle">Seattle</option>
                        <option value="Silicon Valley">Silicon Valley</option>
                        <option value="Washington DC">Washington DC</option>
                    </select>
                    <label class="col1" id="language" for="language">Favorite Language:</label>
                    <select class="col2" name="language">
                        <option value="Javascript">Javascript</option>
                        <option value="Python">Python</option>
                    </select>
                    <label for="comment">Comment (optional):</label>
                    <textarea name="comment"></textarea>
                    <input class="btn" type="submit" value="Submit">
                </form>
            </div>

        </div>
    </body>
</html>

PYTHON-DJANGO/multiple_app_assignment/apps/survey_form/templates/survey_form/result.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Surve Form</title>
    </head>
    <style media="screen">
        * {
            margin: 0;
            padding: 0;
            font-family: monospace;
        }

        .wrapper {
            width: 400px;
            margin: 0 auto;
            padding: 20px;
        }

        h3 {
            text-decoration: underline;
        }

        p {
            margin: 4px 0px;
            vertical-align: top;
        }

            p.col1 {
                margin-left: 8px;
            }

            p.col2 {
                word-wrap: break-word;
            }

        .survey {
            margin: 12px auto;
            padding: 12px;
            border: 1px solid black;
            width: 350px;
            box-sizing: border-box;
        }


        .message {
            background-color: #b6d7a8;
            margin: 8px auto;
            padding: 0px 8px;
            border: 1px solid black;
            width: 350px;
            box-sizing: border-box;
        }


            .col1 {
                width: 45%;
                display: inline-block;
                box-sizing: border-box;

            }


            .col2 {
                margin-left: 1px;
                display: inline-block;
                width: 49%;
                box-sizing: border-box;

            }

            .btn {
                margin-top: 12px;
                width: 20%;
                height: 20px;
                border: 2px solid black;
                box-shadow: 2px 2px black;
                color: white;
                background-color: #2b78e4;
                margin-left: 80%;
            }
    </style>
    <body>
        <div class="wrapper">
            <div class="message">
                <p>Thanks for submitting this form! You have submitted this form {{ request.session.count }} times now.</p>
            </div>
            <div class="survey">
                <form action="{% url 'survey_form:index' %}" method="GET">
                    <h3>Submitted Information</h3>
                    <p class="col1">Name:</p>
                    <p class="col2">{{ request.session.name }}</p>
                    <p class="col1">Dojo Location:</p>
                    <p class="col2">{{ request.session.location }}</p>
                    <p class="col1">Favorite Language:</p>
                    <p class="col2">{{ request.session.language }}</p>
                    <p class="col1">Comment:</p>
                    <p class="col2">{{ request.session.comment }} </p>
                    <input class="btn" type="submit" value="Go Back">
                </form>
            </div>
        </div>
    </body>
</html>