PYTHON-DJANGO/dojo_secrets_assignment/apps/login_registration/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^users$', views.create, name='create'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')

]

PYTHON-DJANGO/dojo_secrets_assignment/dojo_secrets_assignment/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^secrets/', include('apps.dojo_secrets.urls', namespace='dojo_secrets')),
    url(r'^', include('apps.login_registration.urls', namespace='login_registration'))
]

PYTHON-DJANGO/dojo_secrets_assignment/apps/login_registration/models.py
from __future__ import unicode_literals

from django.db import models

import re
import bcrypt

email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):

    def validate_login(self, postData):

        messages = []

        if postData['email'] == "" or not re.match(email_regex, postData['email']) or postData['password'] == "" or len(postData['password']) < 8 or not User.objects.filter(email=postData['email']):
            messages.append('Invalid login')
            return (False, messages)


        get_user = User.objects.filter(email=postData['email'])
        hashed_pw = get_user[0].password.encode()

        if not bcrypt.hashpw(postData['password'].encode(), hashed_pw) == hashed_pw:
            messages.append('Invalid login')
            return (False, messages)

        else:

            user = {

                'id': get_user[0].id,
                'first_name': get_user[0].first_name
            }

            return (True, user)


    def validate_new_user(self, postData):

        messages = []

        if postData['first_name'] == "":
            messages.append('First name cannot be blank')
        elif len(postData['first_name']) < 2:
            messages.append('Please enter a valid first name')

        if postData['last_name'] == "":
            messages.append('Last name cannot be blank')
        elif len(postData['last_name']) < 2:
            messages.append('Please enter a valid last name')

        if postData['email'] == "":
            messages.append('Email cannot be blank')

        elif not re.match(email_regex, postData['email']):
            messages.append('Please enter a valid email')

        elif User.objects.filter(email=postData['email']):
            messages.append('That email already in use')

        if postData['password'] == "":
            messages.append('Password cannot be blank and must be at least 8 characters long')
        elif len(postData['password']) < 8:
            messages.append('Password must be at least 8 characters long')
        elif postData['password'] != postData['confirm_password']:
            messages.append('Password must match confirm password')


        if len(messages) > 0:
            return (False, messages)
        else:
            response = self.add_user(postData)
            return response


    def add_user(self, postData):

        pw_hash = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())

        new_user = User.objects.create(first_name=postData['first_name'], last_name=postData['last_name'], email=postData['email'], password=pw_hash)

        user = {

            'id': new_user.id,
            'first_name': new_user.first_name
        }

        return (True, user)


class User(models.Model):

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __str__(self):

        return self.first_name + " " + self.last_name

PYTHON-DJANGO/dojo_secrets_assignment/apps/login_registration/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages

# Create your views here.
def index(request):

    if 'user' in request.session:

        return redirect('dojo_secrets:index')

    else:

        return render(request, 'login_registration/index.html')


def create(request):

    if request.method != 'POST':
        return redirect('login_registration:index')


    response = User.objects.validate_new_user(request.POST)

    if response[0] == False:

        for message in response[1]:
            messages.error(request, message, extra_tags='registration')

        return redirect('login_registration:index')

    else:

        request.session['user'] = {

            'id': response[1]['id'],
            'first_name': response[1]['first_name']
        }

        return redirect('login_registration:index')


def login(request):

    if request.method != 'POST':
        return redirect('login_registration:index')


    response = User.objects.validate_login(request.POST)

    if response[0] == False:

        for message in response[1]:
            messages.error(request, message, extra_tags='login')
            return redirect('login_registration:index')

    else:

        request.session['user'] = {

            'id': response[1]['id'],
            'first_name': response[1]['first_name']

        }

        return redirect('login_registration:index')


def logout(request):

    request.session.clear()
    return redirect('login_registration:index')

PYTHON-DJANGO/dojo_secrets_assignment/apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Dojo Secrets</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_registration/style.css' %}">
    </head>
    <body>
        <div class="wrapper">
            {% for user in users %}
                <p>{{ user.first_name }} {{ user.email }}</p>
            {% endfor %}

            <div class="login_registration_form">
                <p class="form_heading">Register</p>
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        {% if message.tags == 'registration error' %}
                        <p class="{{ message.tags }}">{{ message }}</p>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                <form action="{% url 'login_registration:create' %}" method="POST">
                    {% csrf_token %}
                    <label for="first_name">First name</label>
                    <input type="text" name="first_name">
                    <label for="last_name">Last name</label>
                    <input type="text" name="last_name">
                    <label for="email">E-mail</label>
                    <input type="text" name="email">
                    <label for="password">Password</label>
                    <input type="password" name="password">
                    <label for="confirm_password">Confirm password</label>
                    <input type="password" name="confirm_password">
                    <input class="btn" type="submit" value="Register">
                </form>
            </div>


            <div class="login_registration_form">
                <p class="form_heading">Log In</p>
                {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        {% if message.tags == 'login error' %}
                        <p class="{{ message.tags}}">{{ message}}</p>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                <form action="{% url 'login_registration:login' %}" method="POST">
                    {% csrf_token %}
                    <label for="email">E-mail</label>
                    <input type="text" name="email">
                    <label for="password">Password</label>
                    <input type="password" name="password">
                    <input class="btn" type="submit" value="Login">
                </form>
            </div>

        </div>
    </body>
</html>